/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-20 13:51:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addBike_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Add Vehicle</title>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f4f7f9;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 650px;\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            padding: 25px;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .image-preview {\r\n");
      out.write("            display: none;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 200px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function previewImage(event) {\r\n");
      out.write("        const preview = document.getElementById('imagePreview');\r\n");
      out.write("        const file = event.target.files[0];\r\n");
      out.write("\r\n");
      out.write("        if (file) {\r\n");
      out.write("            const reader = new FileReader();\r\n");
      out.write("            reader.onload = function() {\r\n");
      out.write("                preview.src = reader.result;\r\n");
      out.write("                preview.style.display = \"block\";\r\n");
      out.write("            }\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        } else {\r\n");
      out.write("            preview.style.display = \"none\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\">Add a New Vehicle</h2>\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"AddBikeServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Vehicle Name -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Name:</label>\r\n");
      out.write("            <input type=\"text\" name=\"name\" class=\"form-control\" placeholder=\"Enter vehicle name\" required>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Vehicle Type -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Type:</label>\r\n");
      out.write("            <select name=\"type\" class=\"form-select\" required>\r\n");
      out.write("                <option value=\"Bike\">Bike</option>\r\n");
      out.write("                <option value=\"Scooty\">Scooty</option>\r\n");
      out.write("                <option value=\"Electric\">Electric</option>\r\n");
      out.write("            </select>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Price -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Price (₹):</label>\r\n");
      out.write("            <input type=\"number\" name=\"price\" class=\"form-control\" placeholder=\"Enter price in INR\" required min=\"1\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Max Power -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Max Power (BHP):</label>\r\n");
      out.write("            <input type=\"text\" name=\"max_power\" class=\"form-control\" placeholder=\"e.g., 20.2 bhp @ 6,100 rpm\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Max Torque -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Max Torque (Nm):</label>\r\n");
      out.write("            <input type=\"text\" name=\"max_torque\" class=\"form-control\" placeholder=\"e.g., 27 Nm @ 4,000 rpm\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Top Speed -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Top Speed (kmph):</label>\r\n");
      out.write("            <input type=\"number\" name=\"top_speed\" class=\"form-control\" placeholder=\"Enter top speed\" min=\"1\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Displacement -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Displacement (cc):</label>\r\n");
      out.write("            <input type=\"text\" name=\"displacement\" class=\"form-control\" placeholder=\"e.g., 349cc\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Fuel Tank Capacity -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Fuel Tank Capacity (liters):</label>\r\n");
      out.write("            <input type=\"number\" name=\"fuel_tank_capacity\" class=\"form-control\" placeholder=\"Enter fuel capacity\" min=\"1\" step=\"0.1\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mileage -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Mileage (kmpl):</label>\r\n");
      out.write("            <input type=\"text\" name=\"mileage\" class=\"form-control\" placeholder=\"Enter mileage\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Image Upload -->\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <label class=\"form-label\">Upload Image:</label>\r\n");
      out.write("            <input type=\"file\" name=\"image\" class=\"form-control\" accept=\".jpg,.jpeg,.png\" required onchange=\"previewImage(event)\">\r\n");
      out.write("            <small class=\"text-muted\">Allowed formats: .jpg, .jpeg, .png</small>\r\n");
      out.write("            <br>\r\n");
      out.write("            <img id=\"imagePreview\" class=\"image-preview\" src=\"#\" alt=\"Image Preview\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary w-100\">Add Vehicle</button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
