/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-22 05:13:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class bikes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>BIKEiT - Home</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background: url('https://www.w3schools.com/w3images/forest.jpg') no-repeat center center fixed;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.7) !important;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 56px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.8);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .container-content {\r\n");
      out.write("            margin-left: 150px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .footer {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("        .sidebar-features {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 56px;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            display: none;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\"><b>BIKEiT</b></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMenu\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarMenu\">\r\n");
      out.write("                <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link active\" href=\"HomePage.jsp\">HOME</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"bookingBike1.jsp\">BOOK NOW</a></li>\r\n");
      out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"emi_cal.jsp\">EMI CALCULATOR</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <form class=\"d-flex\">\r\n");
      out.write("                    <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\">\r\n");
      out.write("                    <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\r\n");
      out.write("                    <a href=\"Login.jsp\" class=\"btn btn-outline-light ms-2\">Login</a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h5>Filter by Price</h5>\r\n");
      out.write("        <input type=\"range\" class=\"form-range\" id=\"priceRange\" min=\"50000\" max=\"600000\" step=\"5000\">\r\n");
      out.write("        <p>Min: ₹<span id=\"minPrice\">50000</span> - Max: ₹<span id=\"maxPrice\">600000</span></p>\r\n");
      out.write("        <h5>Category</h5>\r\n");
      out.write("       <div>\r\n");
      out.write("    <a href=\"scooty.jsp\" class=\"d-block text-light text-decoration-none\">Scooty</a>\r\n");
      out.write("    <a href=\"bikes.jsp\" class=\"d-block text-light text-decoration-none\">Bikes</a>\r\n");
      out.write("    <a href=\"electric.jsp\" class=\"d-block text-light text-decoration-none\">Electric</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <h5>Sort By</h5>\r\n");
      out.write("        <select class=\"form-select\" id=\"sortOrder\">\r\n");
      out.write("            <option value=\"low\">Low to High</option>\r\n");
      out.write("            <option value=\"high\">High to Low</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container container-content\">\r\n");
      out.write("        <div class=\"row justify-content-center\" id=\"bikeContainer\">\r\n");
      out.write("            <div class=\"col-md-4\"  style=\"width:30%\"data-price=\"229746\">\r\n");
      out.write("    <div class=\"card text-dark\">\r\n");
      out.write("        <img src=\"images/b1.jpg\" class=\"card-img-top\" alt=\"Royal Enfield Classic 350\">\r\n");
      out.write("        <div class=\"card-body text-center\">\r\n");
      out.write("            <h5 class=\"card-title\">Royal Enfield Classic 350</h5>\r\n");
      out.write("            <p class=\"card-text\"><b>Price ₹ 2,29,746</b></p>\r\n");
      out.write("            <button class=\"btn btn-primary more-details\" data-id=\"classic350\">More Details</button>\r\n");
      out.write("            <a href=\"emi_cal.jsp\" class=\"btn btn-warning\">Check EMI</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div class=\"col-md-4\" style=\"width:30%\"data-price=\"429746\">\r\n");
      out.write("    <div class=\"card text-dark\">\r\n");
      out.write("        <img src=\"images/b6.jpg\" class=\"card-img-top\" alt=\"Royal Enfield Continental GT 650\">\r\n");
      out.write("        <div class=\"card-body text-center\">\r\n");
      out.write("            <h5 class=\"card-title\">Royal Enfield Continental GT 650</h5>\r\n");
      out.write("            <p class=\"card-text\"><b>Price ₹ 4,29,746</b></p>\r\n");
      out.write("            <button class=\"btn btn-primary more-details\" data-id=\"continentalGT650\">More Details</button>\r\n");
      out.write("            <a href=\"emi_cal.jsp\" class=\"btn btn-warning\">Check EMI</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"col-md-4\" style=\"width:30%\"data-price=\"237624\">\r\n");
      out.write("    <div class=\"card text-dark\">\r\n");
      out.write("        <img src=\"images/b4.jpg\" class=\"card-img-top\" alt=\"Honda CB350\">\r\n");
      out.write("        <div class=\"card-body text-center\">\r\n");
      out.write("            <h5 class=\"card-title\">Honda CB350</h5>\r\n");
      out.write("            <p class=\"card-text\"><b>Price ₹ 2,37,624</b></p>\r\n");
      out.write("            <button class=\"btn btn-primary more-details\" data-id=\"cb350\">More Details</button>\r\n");
      out.write("            <a href=\"emi_cal.jsp\" class=\"btn btn-warning\">Check EMI</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<a href=\"compareBike.jsp\">\r\n");
      out.write(" <button class=\"rounded-circle position-fixed bottom-0 end-0 m-4\"\r\n");
      out.write("        style=\"width: 95px; height: 80px; background-color: #FFBB00; color: black; border: none; text-align:center;\">\r\n");
      out.write("        COMPARE\r\n");
      out.write("    </button>\r\n");
      out.write("</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"text-center text-light\" id=\"noBikesMessage\" style=\"display: none;\">No bikes available in this range</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar-features\" id=\"sidebarFeatures\">\r\n");
      out.write("        <h4>Bike Details</h4>\r\n");
      out.write("        <div id=\"featureContent\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <p>&copy; 2025 BIKEiT | All Rights Reserved</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    document.querySelectorAll(\".more-details\").forEach(button => {\r\n");
      out.write("        button.addEventListener(\"click\", function() {\r\n");
      out.write("            let sidebar = document.getElementById(\"sidebarFeatures\");\r\n");
      out.write("            let featureContent = document.getElementById(\"featureContent\");\r\n");
      out.write("\r\n");
      out.write("            let details = {\r\n");
      out.write("            		classic350: `<p><b>Royal Enfield Classic 350</b></p>\r\n");
      out.write("                        <p>Engine: 349cc</p>\r\n");
      out.write("                        <p>Mileage: 35 kmpl</p>\r\n");
      out.write("                        <p>Top Speed: 120 km/h</p>\r\n");
      out.write("                        <p>Fuel Tank: 13L</p>\r\n");
      out.write("                        <button class=\"btn btn-danger close-sidebar\">Close</button>\r\n");
      out.write("                        <a href=\"bookingBike1.jsp?bike=Royal Enfield Classic 350\" class=\"btn btn-success ms-2\">Book Now</a>`,\r\n");
      out.write("                    continentalGT650: `<p><b>Royal Enfield Continental GT 650</b></p>\r\n");
      out.write("                        <p>Engine: 648cc</p>\r\n");
      out.write("                        <p>Mileage: 27 kmpl</p>\r\n");
      out.write("                        <p>Top Speed: 160 km/h</p>\r\n");
      out.write("                        <p>Fuel Tank: 12.5L</p>\r\n");
      out.write("                        <button class=\"btn btn-danger close-sidebar\">Close</button>\r\n");
      out.write("                        <a href=\"bookingBike2.jsp?bike=Royal Enfield Continental GT 650\" class=\"btn btn-success ms-2\">Book Now</a>`,\r\n");
      out.write("                    cb350: `<p><b>Honda CB350</b></p>\r\n");
      out.write("                   		<p>Engine: 348cc</p>\r\n");
      out.write("                 	    <p>Mileage: 40 kmpl</p>\r\n");
      out.write("                   	    <p>Top Speed: 110 km/h</p>\r\n");
      out.write("                	    <p>Fuel Tank: 15L</p>\r\n");
      out.write("                 	    <button class=\"btn btn-danger close-sidebar\">Close</button>\r\n");
      out.write("                        <a href=\"bookingBike3.jsp?bike=Honda CB350\" class=\"btn btn-success ms-2\">Book Now</a>`\r\n");
      out.write("            };\r\n");
      out.write("\r\n");
      out.write("            featureContent.innerHTML = details[this.dataset.id];\r\n");
      out.write("            sidebar.style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("            document.querySelector(\".close-sidebar\").addEventListener(\"click\", function() {\r\n");
      out.write("                sidebar.style.display = \"none\";\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"priceRange\").addEventListener(\"input\", function() {\r\n");
      out.write("        let maxPrice = this.value;\r\n");
      out.write("        document.getElementById(\"maxPrice\").textContent = maxPrice;\r\n");
      out.write("        filterAndSortBikes();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById(\"sortOrder\").addEventListener(\"change\", function() {\r\n");
      out.write("        filterAndSortBikes();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function filterAndSortBikes() {\r\n");
      out.write("        let maxPrice = document.getElementById(\"priceRange\").value;\r\n");
      out.write("        let sortOrder = document.getElementById(\"sortOrder\").value;\r\n");
      out.write("        let bikes = [...document.querySelectorAll(\"#bikeContainer .col-md-4\")];\r\n");
      out.write("\r\n");
      out.write("        bikes.forEach(bike => bike.style.display = parseInt(bike.dataset.price) <= maxPrice ? \"block\" : \"none\");\r\n");
      out.write("\r\n");
      out.write("        bikes.sort((a, b) => sortOrder === \"low\" ? a.dataset.price - b.dataset.price : b.dataset.price - a.dataset.price)\r\n");
      out.write("             .forEach(bike => document.getElementById(\"bikeContainer\").appendChild(bike));\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
