/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-20 17:00:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class bookingScooty2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Booking Page</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Lora:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Lora', serif;\r\n");
      out.write("            background-color: #FFBB00;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            background: #FAF9F6;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            max-width: 500px;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            background: #ff9800;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .product-details {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .product-details img {\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background: #ff9800;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("            margin: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background: #e68900;\r\n");
      out.write("        }\r\n");
      out.write("        .receipt-container {\r\n");
      out.write("            display: none;\r\n");
      out.write("            background: white;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("        .receipt-container p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .hidden {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    function bookNow() {\r\n");
      out.write("        const orderId = 'ORDER-' + Math.floor(Math.random() * 1000000);\r\n");
      out.write("        const bookingDate = new Date().toLocaleDateString();\r\n");
      out.write("        const nearestStore = 'XYZ Bike Store, Main Street';\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('booking-id').innerText = orderId;\r\n");
      out.write("        document.getElementById('receipt-booking-date').innerText = bookingDate;\r\n");
      out.write("        document.getElementById('receipt-location').innerText = nearestStore;\r\n");
      out.write("        document.getElementById('receipt-username').innerText = document.getElementById('username').innerText || \"N/A\";\r\n");
      out.write("        document.getElementById('receipt-bike-id').innerText = document.getElementById('bike-id').innerText || \"N/A\";\r\n");
      out.write("        document.getElementById('receipt-product-name').innerText = document.getElementById('product-name')?.innerText || \"N/A\";\r\n");
      out.write("        document.getElementById('receipt-product-price').innerText = document.getElementById('product-price')?.innerText || \"N/A\";\r\n");
      out.write("\r\n");
      out.write("        document.getElementById('receipt-container').style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function printReceipt() {\r\n");
      out.write("        window.print();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function closeReceipt() {\r\n");
      out.write("        document.getElementById('receipt-container').style.display = \"none\";\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h1>Product Booking</h1>\r\n");
      out.write("        <div class=\"product-details\">\r\n");
      out.write("            <img class=\"product-details-image\" src=\"b7.jpg\" alt=\"Product Image\" width=\"120\" height=\"80\" />\r\n");
      out.write("            <p><strong>Bike ID:</strong> <span id=\"bike-id\">1010</span></p>\r\n");
      out.write("            <p><strong>Username:</strong> <span id=\"username\">Geeta Kapoor</span></p>\r\n");
      out.write("            <p><strong>Product Name:</strong> <span id=\"product-name\">Honda Activa</span></p>\r\n");
      out.write("            <p><strong>Price:</strong> <span id=\"product-price\">₹ 1,37,624</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button onclick=\"bookNow()\">Book Now</button>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"receipt-container\" class=\"receipt-container hidden\">\r\n");
      out.write("            <h2>Receipt</h2>\r\n");
      out.write("            <p><strong>Order ID:</strong> <span id=\"booking-id\"></span></p>\r\n");
      out.write("            <p><strong>Username:</strong> <span id=\"receipt-username\"></span></p>\r\n");
      out.write("            <p><strong>Bike ID:</strong> <span id=\"receipt-bike-id\"></span></p>\r\n");
      out.write("            <p><strong>Product Name:</strong> <span id=\"receipt-product-name\"></span></p>\r\n");
      out.write("            <p><strong>Price:</strong> <span id=\"receipt-product-price\"></span></p>\r\n");
      out.write("            <p><strong>Booking Date:</strong> <span id=\"receipt-booking-date\"></span></p>\r\n");
      out.write("            <p><strong>Nearest Store:</strong> <span id=\"receipt-location\"></span></p>\r\n");
      out.write("            <button onclick=\"printReceipt()\">Print Receipt</button>\r\n");
      out.write("            <button onclick=\"closeReceipt()\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
