/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-20 16:49:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class compareScooty_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Comparison</title>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	background: url('https://www.w3schools.com/w3images/forest.jpg')\r\n");
      out.write("		no-repeat center center fixed;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	max-width: 800px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".comparison-table {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card {\r\n");
      out.write("	background-color: #fff;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	padding: 20px;\r\n");
      out.write("	width: 45%;\r\n");
      out.write("	box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	transition: transform 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card:hover {\r\n");
      out.write("	transform: scale(1.02);\r\n");
      out.write("	border-color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card h2 {\r\n");
      out.write("	color: #000000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card ul {\r\n");
      out.write("	list-style-type: none;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".product-card li {\r\n");
      out.write("	margin: 10px 0;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("	height: 200px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	background-color: rgb(179, 0, 0);\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".specs {\r\n");
      out.write("	display: none;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	background-color: #e9ecef;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("        function toggleSpecs1(product) {\r\n");
      out.write("            const specs1 = document.getElementById(product + '-specs1');\r\n");
      out.write("            if (specs1.style.display === \"none\" || specs1.style.display === \"\") {\r\n");
      out.write("                specs1.style.display = \"block\";\r\n");
      out.write("            } else {\r\n");
      out.write("                specs1.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function toggleSpecs2(product) {\r\n");
      out.write("            const Specs2 = document.getElementById(product + '-specs2');\r\n");
      out.write("            if (Specs2.style.display === \"none\" || Specs2.style.display === \"\") {\r\n");
      out.write("                Specs2.style.display = \"block\";\r\n");
      out.write("            } else {\r\n");
      out.write("                Specs2.style.display = \"none\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<h1>TVS Jupiter VS Honda Activa</h1>\r\n");
      out.write("		<div class=\"comparison-table\">\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<img src=\"images/b5.jpg\" alt=\"TVS Jupiter\">\r\n");
      out.write("				<hr>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><b>TVS Jupiter</b></li>\r\n");
      out.write("					<li><strong>Price:</strong>₹ 76,738</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<button class=\"dropdown\" onclick=\"toggleSpecs1('productA')\">Power\r\n");
      out.write("					and Performance</button>\r\n");
      out.write("				<div id=\"productA-specs1\" class=\"specs\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><strong>Max Power:</strong> 7.88 bhp @ 7,500 rpm</li>\r\n");
      out.write("						<li><strong>Max Torque:</strong> 8.8 Nm @ 5,500 rpm</li>\r\n");
      out.write("						<li><strong>Top Speed:</strong> 85 km/h</li>\r\n");
      out.write("						<li><strong>Displacement:</strong> 109.7cc</li>\r\n");
      out.write("						<li><strong>Fuel Tank Capacity:</strong> 6 liters</li>\r\n");
      out.write("						<li><strong>Mileage:</strong> 50 kmpl</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<button class=\"dropdown\" onclick=\"toggleSpecs2('productA')\">Brakes,\r\n");
      out.write("					Wheels Suspension</button>\r\n");
      out.write("				<div id=\"productA-specs2\" class=\"specs\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><strong>Front Suspension:</strong> Telescopic Hydraulic Fork</li>\r\n");
      out.write("						<li><strong>Rear Suspension:</strong> 3-Step Adjustable Gas Charged Monoshock</li>\r\n");
      out.write("						<li><strong>Braking System:</strong> Synchronized Braking System (SBS)</li>\r\n");
      out.write("						<li><strong>Front Brake Type:</strong> Drum</li>\r\n");
      out.write("						<li><strong>Wheel Type:</strong> Alloy</li>\r\n");
      out.write("						<li><strong>Tyre Type:</strong> Tubeless</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"product-card\">\r\n");
      out.write("				<img src=\"images/b7.jpg\" alt=\"Honda Activa\">\r\n");
      out.write("				<hr>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><b>Honda Activa</b></li>\r\n");
      out.write("					<li><strong>Price:</strong>₹ 78,920</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<button class=\"dropdown\" onclick=\"toggleSpecs1('productB')\">Power\r\n");
      out.write("					and Performance</button>\r\n");
      out.write("				<div id=\"productB-specs1\" class=\"specs\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><strong>Max Power:</strong> 7.68 bhp @ 8,000 rpm</li>\r\n");
      out.write("						<li><strong>Max Torque:</strong> 8.84 Nm @ 5,500 rpm</li>\r\n");
      out.write("						<li><strong>Top Speed:</strong> 85 km/h</li>\r\n");
      out.write("						<li><strong>Displacement:</strong> 109.51cc</li>\r\n");
      out.write("						<li><strong>Fuel Tank Capacity:</strong> 5.3 liters</li>\r\n");
      out.write("						<li><strong>Mileage:</strong> 45 kmpl</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"dropdown\" onclick=\"toggleSpecs2('productB')\">Brakes,\r\n");
      out.write("					Wheels Suspension</button>\r\n");
      out.write("				<div id=\"productB-specs2\" class=\"specs\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><strong>Front Suspension:</strong> Telescopic Front Forks</li>\r\n");
      out.write("						<li><strong>Rear Suspension:</strong> 3-Step Adjustable Spring Loaded Hydraulic</li>\r\n");
      out.write("						<li><strong>Braking System:</strong> Combi Brake System (CBS)</li>\r\n");
      out.write("						<li><strong>Front Brake Type:</strong> Drum</li>\r\n");
      out.write("						<li><strong>Wheel Type:</strong> Steel</li>\r\n");
      out.write("						<li><strong>Tyre Type:</strong> Tubeless</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
