/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-21 14:29:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class electric_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>BIKEiT - Home</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        background: url('https://www.w3schools.com/w3images/forest.jpg') no-repeat center center fixed;\r\n");
      out.write("            /*background-color:#faf9f6;*/\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background-color: black ;\r\n");
      out.write("            color:#FFBB00;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 200px;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 56px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background: black;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .container-content {\r\n");
      out.write("            margin-left: 270px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            transition: transform 0.3s;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        .footer {\r\n");
      out.write("            background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .feature-dropdown {\r\n");
      out.write("            display: none;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            color: black;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-features {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 56px;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            display: none;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("       .footer {\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 0.9rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\"><b>BIKEiT</b></a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarMenu\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarMenu\">\r\n");
      out.write("                <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("                     <li class=\"nav-item\"><a class=\"nav-link active\" href=\"HomePage.jsp\">HOME</a></li>\r\n");
      out.write("                   <li class=\"nav-item\"><a class=\"nav-link\" href=\"booking.jsp\">BOOK NOW</a></li>\r\n");
      out.write("                   <li class=\"nav-item\"><a class=\"nav-link\" href=\"emi_cal.jsp\">EMI CALCULATOR</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <form class=\"d-flex\">\r\n");
      out.write("                    <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\">\r\n");
      out.write("                    <button class=\"btn btn-outline-light\" type=\"submit\">Search</button>\r\n");
      out.write("                    <a href=\"Login.jsp\" class=\"btn btn-outline-light ms-2\">Login</a>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <h5>Filter by Price</h5>\r\n");
      out.write("        <input type=\"range\" class=\"form-range\" id=\"priceRange\" min=\"50000\" max=\"300000\" step=\"5000\">\r\n");
      out.write("        <p>Min: ₹<span id=\"minPrice\">50000</span> - Max: ₹<span id=\"maxPrice\">300000</span></p>\r\n");
      out.write("        <h5>Category</h5>\r\n");
      out.write("        <div>\r\n");
      out.write("            <a href=\"scooty.jsp\" class=\"d-block text-light\">Scooty</a>\r\n");
      out.write("            <a href=\"bikes.jsp\" class=\"d-block text-light\">Bikes</a>\r\n");
      out.write("            <a href=\"electric.jsp\" class=\"d-block text-light\">Electric</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <h5>Sort By</h5>\r\n");
      out.write("        <select class=\"form-select\" id=\"sortOrder\">\r\n");
      out.write("            <option value=\"low\">Low to High</option>\r\n");
      out.write("            <option value=\"high\">High to Low</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container container-content\">\r\n");
      out.write("        <div class=\"row justify-content-center\" id=\"bikeContainer\">\r\n");
      out.write("            <div class=\"col-md-4\" data-price=\"229746\">\r\n");
      out.write("                <div class=\"card text-dark\">\r\n");
      out.write("                    <img src=\"images/b2.jpg\" class=\"card-img-top\" alt=\"Bike\">\r\n");
      out.write("                    <div class=\"card-body text-center\">\r\n");
      out.write("                        <h5 class=\"card-title\">OLA</h5>\r\n");
      out.write("                        <p class=\"card-text\"><b>Price ₹ 2,29,746</b></p>\r\n");
      out.write("                        <div class=\"btn-group\">\r\n");
      out.write("                            <button class=\"btn btn-primary add-to-cart\" data-id=\"bike1\">More Details</button>\r\n");
      out.write("                            <a href=\"emi_cal.jsp\" class=\"btn btn-warning\">Check EMI</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <p class=\"text-center text-light\" id=\"noBikesMessage\" style=\"display: none;\">No bikes available in this range</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"sidebar-features\" id=\"sidebarFeatures\">\r\n");
      out.write("        <h4>Bike Details</h4>\r\n");
      out.write("        <div id=\"featureContent\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <p>&copy; 2025 BIKEiT | All Rights Reserved</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    document.querySelectorAll(\".add-to-cart\").forEach(button => {\r\n");
      out.write("        button.addEventListener(\"click\", function() {\r\n");
      out.write("            let sidebar = document.getElementById(\"sidebarFeatures\");\r\n");
      out.write("            let featureContent = document.getElementById(\"featureContent\");\r\n");
      out.write("\r\n");
      out.write("            // Toggle functionality: Hide if already open\r\n");
      out.write("            if (sidebar.style.display === \"block\") {\r\n");
      out.write("                sidebar.style.display = \"none\";\r\n");
      out.write("            } else {\r\n");
      out.write("                featureContent.innerHTML = `\r\n");
      out.write("                    <p><b>OLA</b></p>\r\n");
      out.write("                    <p>Range: 120 km</p>\r\n");
      out.write("                    <p>Top Speed: 90 km/h</p>\r\n");
      out.write("                    <p>Battery: 4 kWh</p>\r\n");
      out.write("                    <p>Charging Time: 4 hours</p>\r\n");
      out.write("                    <a href=\"bookingElectric.jsp\" class=\"btn btn-success\">Book Now</a>\r\n");
      out.write("                    <button class=\"btn btn-danger close-sidebar\">Close</button>\r\n");
      out.write("                `;\r\n");
      out.write("                sidebar.style.display = \"block\";\r\n");
      out.write("\r\n");
      out.write("                // Close button functionality\r\n");
      out.write("                document.querySelector(\".close-sidebar\").addEventListener(\"click\", function() {\r\n");
      out.write("                    sidebar.style.display = \"none\";\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        document.querySelectorAll(\".emi-calculator\").forEach(button => {\r\n");
      out.write("            button.addEventListener(\"click\", function() {\r\n");
      out.write("                alert(\"EMI Calculator Feature Coming Soon!\");\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        window.addEventListener(\"resize\", function() {\r\n");
      out.write("            document.querySelector(\".footer\").style.position = document.body.offsetHeight < window.innerHeight ? \"fixed\" : \"relative\";\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
