/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-21 08:36:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class HomePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>BIKEiT</title>\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Rufina:400,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css\" />\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/linearicons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/owl.theme.default.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootsnav.css\">\r\n");
      out.write("    <!--  <link rel=\"stylesheet\" href=\"assets/css/style.css\">-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/responsive.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles1.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Welcome Hero Start -->\r\n");
      out.write("    <section id=\"home\" class=\"welcome-hero\">\r\n");
      out.write("        <div class=\"top-area\">\r\n");
      out.write("            <div class=\"header-area\">\r\n");
      out.write("                <nav class=\"navbar navbar-default bootsnav navbar-sticky navbar-scrollspy\" data-minus-value-desktop=\"70\" data-minus-value-mobile=\"55\" data-speed=\"1000\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"navbar-header\">\r\n");
      out.write("                            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-menu\">\r\n");
      out.write("                                <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <a class=\"navbar-brand\" href=\"HomePage.jsp\">BIKEiT<span></span></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"collapse navbar-collapse menu-ui-design\" id=\"navbar-menu\">\r\n");
      out.write("                            <ul class=\"nav navbar-nav navbar-right\" data-in=\"fadeInDown\" data-out=\"fadeOutUp\">\r\n");
      out.write("                                <li><a href=\"#home\">Home</a></li>\r\n");
      out.write("                                <li><a href=\"bikes.jsp\">Bikes</a></li>\r\n");
      out.write("                                <li><a href=\"scooty.jsp\">Scooty</a></li>\r\n");
      out.write("                                <li><a href=\"electric.jsp\">Electric</a></li>\r\n");
      out.write("                                <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("                                <li><a href=\"Register.jsp\">Register</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </nav>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"welcome-hero-txt\">\r\n");
      out.write("                <h1>Welcome to BIKEiT</h1>\r\n");
      out.write("                <h1><span>Your One-Stop Shop</span> for Bikes and Scooty</h1>\r\n");
      out.write("                <h3>Explore our wide range of bikes, scooty, and electric vehicles.</h3>\r\n");
      out.write("                <br>\r\n");
      out.write("                <button class=\"welcome-btn\" onclick=\"window.location.href='compareBike.jsp'\">Compare bikes</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Welcome Hero End -->\r\n");
      out.write("    <!-- Service Section Start -->\r\n");
      out.write("    <section id=\"service\" class=\"service\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"service-content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-service-item\">\r\n");
      out.write("                            <div class=\"single-service-icon\">\r\n");
      out.write("                                <i class=\"fas fa-motorcycle\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h2><a href=\"#\">Largest Dealership <span>of</span> Bikes</a></h2>\r\n");
      out.write("                            <p>We offer a wide range of bikes from various brands, ensuring you find the perfect ride for your needs.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-service-item\">\r\n");
      out.write("                            <div class=\"single-service-icon\">\r\n");
      out.write("                                <i class=\"fas fa-tools\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h2><a href=\"#\">Unlimited Repair Warranty</a></h2>\r\n");
      out.write("                            <p>Enjoy peace of mind with our unlimited repair warranty on all bikes purchased from us.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-service-item\">\r\n");
      out.write("                            <div class=\"single-service-icon\">\r\n");
      out.write("                                <i class=\"fas fa-shield-alt\"></i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h2><a href=\"#\">Insurance Support</a></h2>\r\n");
      out.write("                            <p>We provide comprehensive insurance support to help you protect your investment.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Service End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- New Bikes Start -->\r\n");
      out.write("    <section id=\"new-bikes\" class=\"new-bikes\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <p>Checkout <span>the</span> Latest Bikes</p>\r\n");
      out.write("                <h2>Newest Bikes</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"new-bikes-content\">\r\n");
      out.write("                <div class=\"owl-carousel owl-theme\" id=\"new-bikes-carousel\">\r\n");
      out.write("                    <div class=\"new-bikes-item\">\r\n");
      out.write("                        <div class=\"single-new-bikes-item\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-7 col-sm-12\">\r\n");
      out.write("                                    <div class=\"new-bikes-img\">\r\n");
      out.write("                                        <img src=\"./images/b8.jpg\" alt=\"Yamaha MT-15\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-5 col-sm-12\">\r\n");
      out.write("                                    <div class=\"new-bikes-txt\">\r\n");
      out.write("                                        <h2><a href=\"#\">Yamaha MT-15</a></h2>\r\n");
      out.write("                                        <p>The Yamaha MT 15 needs no real introduction, but let’s give you a little back story to jog your memory. So, the MT 15 was launched in India in 2019 as a city-friendly alternative to the ever-popular and particularly track-focused R15 V3 which proved its performance and handling mettle time and again.</p>\r\n");
      out.write("                                        <button class=\"welcome-btn new-bikes-btn\" onclick=\"window.location.href='#'\">View Details</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"new-bikes-item\">\r\n");
      out.write("                        <div class=\"single-new-bikes-item\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-7 col-sm-12\">\r\n");
      out.write("                                    <div class=\"new-bikes-img\">\r\n");
      out.write("                                        <img src=\"./images/b10.jpg\" alt=\"KTM Duke 390\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-5 col-sm-12\">\r\n");
      out.write("                                    <div class=\"new-bikes-txt\">\r\n");
      out.write("                                        <h2><a href=\"#\">KTM Duke 390</a></h2>\r\n");
      out.write("                                        <p>Every once in a while, there comes a motorcycle that is very special and sets new benchmarks in the segment. The KTM 390 Duke is one such motorcycle. Back when the first-gen Duke 390 was launched in India in 2013, it brought performance motorcycling to the masses. The Duke was unabashedly raw, menacingly fast, and extremely pocket-friendly. </p>\r\n");
      out.write("                                        <button class=\"welcome-btn new-bikes-btn\" onclick=\"window.location.href='#'\">View Details</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"new-bikes-item\">\r\n");
      out.write("                        <div class=\"single-new-bikes-item\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-7 col-sm-12\">\r\n");
      out.write("                                    <div class=\"new-bikes-img\">\r\n");
      out.write("                                        <img src=\"./images/b9.jpg\" alt=\"Honda CB Shine\" />\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-5 col-sm-12\">\r\n");
      out.write("                                    <div class=\"new-bikes-txt\">\r\n");
      out.write("                                        <h2><a href=\"#\">Honda CB Shine</a></h2>\r\n");
      out.write("                                        <p>The CB Shine is one easy to run and maintain 125cc motorcycle. It is known for its refined motor, and a ride quality that makes daily commuting an easy affair. But it lacks features. </p>\r\n");
      out.write("                                        <button class=\"welcome-btn new-bikes-btn\" onclick=\"window.location.href='#'\">View Details</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Featured Bikes Start -->\r\n");
      out.write("    <section id=\"featured-bikes\" class=\"featured-bikes\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"section-header\">\r\n");
      out.write("                <p>Checkout <span>the</span> Featured Bikes</p>\r\n");
      out.write("                <h2>Featured Bikes</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"featured-bikes-content\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-featured-bikes\">\r\n");
      out.write("                            <div class=\"featured-img-box\">\r\n");
      out.write("                                <div class=\"featured-bikes-img\">\r\n");
      out.write("                                    <img src=\"./images/b11.jpg\" alt=\"bikes\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"featured-model-info\">\r\n");
      out.write("                                    <p>Model: 2022 <span class=\"featured-mi-span\"> 1500 mi</span> <span class=\"featured-hp-span\"> 20HP</span></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"featured-bikes-txt\">\r\n");
      out.write("                                <h2><a href=\"#\">Bajaj Pulsar NS200</a></h2>\r\n");
      out.write("                                <h3>₹ 1,69,219</h3>\r\n");
      out.write("                                <p>Bajaj gave the Pulsar NS200 some of its biggest upgrades like upside-down front forks and preload adjustment at the back. These changes have made the motorcycle much better when it comes to riding in the city.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-featured-bikes\">\r\n");
      out.write("                            <div class=\"featured-img-box\">\r\n");
      out.write("                                <div class=\"featured-bikes-img\">\r\n");
      out.write("                                    <img src=\"./images/b14.jpg\" alt=\"bikes\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"featured-model-info\">\r\n");
      out.write("                                    <p>Model: 2022 <span class=\"featured-mi-span\"> 1200 mi</span> <span class=\"featured-hp-span\"> 25HP</span></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"featured-bikes-txt\">\r\n");
      out.write("                                <h2><a href=\"#\">TVS Apache RTR 200</a></h2>\r\n");
      out.write("                                <h3>₹ 1,76,157</h3>\r\n");
      out.write("                                <p>This is the TVS Apache RTR 200 4V and it needs no introduction. It is undoubtedly one of the most accomplished motorcycles in its class, mainly due to its sporty styling, peppy performance, and a long list of features.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-featured-bikes\">\r\n");
      out.write("                            <div class=\"featured-img-box\">\r\n");
      out.write("                                <div class=\"featured-bikes-img\">\r\n");
      out.write("                                    <img src=\"./images/b13.jpg\" alt=\"bikes\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"featured-model-info\">\r\n");
      out.write("                                    <p>Model: 2022 <span class=\"featured-mi-span\"> 800 mi</span> <span class=\"featured-hp-span\"> 15HP</span></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"featured-bikes-txt\">\r\n");
      out.write("                                <h2><a href=\"#\">Hero Splendor Plus</a></h2>\r\n");
      out.write("                                <h3>₹ 95,993</h3>\r\n");
      out.write("                                <p>The Splendor Plus has been Hero Motocorp’s best-selling product in India for years now, mainly for its reliability and frugal engine, which make it an ideal workhorse. Hero’s massive service network and affordable ownership experience also play a part in Splendor’s long-running success. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-featured-bikes\">\r\n");
      out.write("                            <div class=\"featured-img-box\">\r\n");
      out.write("                                <div class=\"featured-bikes-img\">\r\n");
      out.write("                                    <img src=\"./images/b12.jpg\" alt=\"bikes\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"featured-model-info\">\r\n");
      out.write("                                    <p>Model: 2022 <span class=\"featured-mi-span\"> 500 mi</span> <span class=\"featured-hp-span\"> 30HP</span></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"featured-bikes-txt\">\r\n");
      out.write("                                <h2><a href=\"#\">Kawasaki Ninja 300</a></h2>\r\n");
      out.write("                                <h3>₹ 4,30,000\r\n");
      out.write("                                </h3>\r\n");
      out.write("                                <p>The Ninja 300 is Kawasaki's smallest fully-faired offering belonging to the Ninja series. It packs a potent parallel-twin motor, striking looks and distinct exhaust note, all available at a premium price. But the overall maintenance is a bit on the higher side. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Featured Bikes End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Clients Say Start -->\r\n");
      out.write("   <section id=\"clients-say\" class=\"clients-say\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"section-header\">\r\n");
      out.write("            <h2>What Our Clients Say</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"owl-carousel testimonial-carousel\">\r\n");
      out.write("                <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("                    <div class=\"single-testimonial-box\">\r\n");
      out.write("                        <div class=\"testimonial-description\">\r\n");
      out.write("                            <div class=\"testimonial-info\">\r\n");
      out.write("                                <div class=\"testimonial-img\">\r\n");
      out.write("                                    <img src=\"assets/images/clients/c1.png\" alt=\"image of clients person\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"testimonial-comment\">\r\n");
      out.write("                                <p>\"The service was exceptional, and the support team was always available to assist me whenever needed. A great experience overall!\"</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"testimonial-person\">\r\n");
      out.write("                                <h2><a href=\"#\">Aarav Sharma</a></h2>\r\n");
      out.write("                                <h4>Mumbai</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("                    <div class=\"single-testimonial-box\">\r\n");
      out.write("                        <div class=\"testimonial-description\">\r\n");
      out.write("                            <div class=\"testimonial-info\">\r\n");
      out.write("                                <div class=\"testimonial-img\">\r\n");
      out.write("                                    <img src=\"assets/images/clients/c2.png\" alt=\"image of clients person\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"testimonial-comment\">\r\n");
      out.write("                                <p>\"I was really impressed with the product quality. The team went above and beyond to ensure my satisfaction. Highly recommended!\"</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"testimonial-person\">\r\n");
      out.write("                                <h2><a href=\"#\">Priya Patel</a></h2>\r\n");
      out.write("                                <h4>Delhi</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-3 col-xs-12\">\r\n");
      out.write("                    <div class=\"single-testimonial-box\">\r\n");
      out.write("                        <div class=\"testimonial-description\">\r\n");
      out.write("                            <div class=\"testimonial-info\">\r\n");
      out.write("                                <div class=\"testimonial-img\">\r\n");
      out.write("                                    <img src=\"assets/images/clients/c3.png\" alt=\"image of clients person\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"testimonial-comment\">\r\n");
      out.write("                                <p>\"Amazing customer service! They were prompt in resolving issues and made sure everything went smoothly. I’ll definitely return!\"</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"testimonial-person\">\r\n");
      out.write("                                <h2><a href=\"#\">Ravi Kumar</a></h2>\r\n");
      out.write("                                <h4>Bangalore</h4>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> \r\n");
      out.write("                <!-- Closing for Ravi Kumar's div -->\r\n");
      out.write("            </div> <!-- Closing for .owl-carousel -->\r\n");
      out.write("        </div> <!-- Closing for .row -->\r\n");
      out.write("    </div> <!-- Closing for .container -->\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("    <section id=\"brand\" class=\"brand\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"brand-area\">\r\n");
      out.write("                <div class=\"owl-carousel owl-theme brand-item\">\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/brand/bajaj.png\" alt=\"Yamaha\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/brand/ktm.png\" alt=\"KTM\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/brand/IMG-20250217-WA0012.jpg\" alt=\"Honda\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/brand/IMG-20250217-WA0013.jpg\" alt=\"Bajaj\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/brand/IMG-20250217-WA0014.jpg\" alt=\"Suzuki\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/brand/r1.jpg\" alt=\"Royal Enfield\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Contact Start -->\r\n");
      out.write("    <footer id=\"contact\" class=\"contact\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-top\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget\">\r\n");
      out.write("                            <div class=\"footer-logo\">\r\n");
      out.write("                                <a href=\"index.html\">BIKEiT</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <p>Explore our wide range of bikes, scooty, and electric vehicles.</p>\r\n");
      out.write("                            <div class=\"footer-contact\">\r\n");
      out.write("                                <p>info@bikeit.com</p>\r\n");
      out.write("                                <p>+1 (885) 2563154554</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-2 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget\">\r\n");
      out.write("                            <h2>About Us</h2>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Career</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Terms of Service</a></li>\r\n");
      out.write("                                <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-3 col-xs-12\">\r\n");
      out.write("                        <div class=\"single-footer-widget\">\r\n");
      out.write("                            <h2>Top Brands</h2>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-7 col-xs-6\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Yamaha</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Kawasaki</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Honda</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Bajaj</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">TVS</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Hero</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-5 col-xs-6\">\r\n");
      out.write("                                    <ul>\r\n");
      out.write("                                        <li><a href=\"#\">Suzuki</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Ducati</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">KTM</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">BMW</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Triumph</a></li>\r\n");
      out.write("                                        <li><a href=\"#\">Royal Enfield</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-offset-1 col-md-3 col-sm-6\">\r\n");
      out.write("                        <div class=\"single-footer-widget\">\r\n");
      out.write("                            <h2>Newsletter</h2>\r\n");
      out.write("                            <div class=\"footer-newsletter\">\r\n");
      out.write("                                <p>Subscribe to get the latest news updates and information</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"hm-foot-email\">\r\n");
      out.write("                                <div class=\"foot-email-box\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" placeholder=\"Add Email\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"foot-email-subscribe\">\r\n");
      out.write("                                    <span><i class=\"fa fa-arrow-right\"></i></span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-copyright\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                        <p>&copy; copyright. Designed and developed by <a href=\"#\">BIKEiT</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-sm-6\">\r\n");
      out.write("                        <div class=\"footer-social\">\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-facebook\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-instagram\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-pinterest-p\"></i></a>\r\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-behance\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"assets/js/jquery.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootsnav.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function() {\r\n");
      out.write("            $(\"#new-bikes-carousel\").owlCarousel({\r\n");
      out.write("                items: 1,\r\n");
      out.write("                loop: true,\r\n");
      out.write("                autoplay: true,\r\n");
      out.write("                autoplayTimeout: 1000,\r\n");
      out.write("                autoplayHoverPause: true,\r\n");
      out.write("                nav: true,\r\n");
      out.write("                dots: true,\r\n");
      out.write("                responsive: {\r\n");
      out.write("                    0: {\r\n");
      out.write("                        items: 1\r\n");
      out.write("                    },\r\n");
      out.write("                    600: {\r\n");
      out.write("                        items: 1\r\n");
      out.write("                    },\r\n");
      out.write("                    1000: {\r\n");
      out.write("                        items: 1\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
