/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.0-M22
 * Generated at: 2025-03-16 08:49:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String errorMessage = request.getParameter("error");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("    background: url('https://www.w3schools.com/w3images/forest.jpg') no-repeat center center fixed;\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#log {\r\n");
      out.write("    border: 5px solid #FFBB00;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding: 40px;\r\n");
      out.write("    background-color: rgba(252, 246, 245, 0.95);\r\n");
      out.write("    box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("    font-family: 'Lucida Grande';\r\n");
      out.write("    color: #FFBB00;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-item .nav-link {\r\n");
      out.write("    color: #FFBB00 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-item .nav-link:hover {\r\n");
      out.write("    color: #FFD700 !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark\" style=\"background-color: #000;\">\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <h1>BIKEiT</h1>\r\n");
      out.write("               \r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("                    data-bs-toggle=\"collapse\" data-bs-target=\"#navbar-menu\"\r\n");
      out.write("                    aria-controls=\"navbar-menu\" aria-expanded=\"false\"\r\n");
      out.write("                    aria-label=\"Toggle navigation\">\r\n");
      out.write("                    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbar-menu\">\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"HomePage.jsp\">Home</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"Features.jsp\">Features</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"About.jsp\">About</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"Contact.jsp\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Login Form Start -->\r\n");
      out.write("    <div class=\"row mt-5\">\r\n");
      out.write("        <div class=\"col-md-4\"></div>\r\n");
      out.write("        <div class=\"col-md-4\">\r\n");
      out.write("            <form action=\"LoginServlet\" method=\"post\" id=\"log\">\r\n");
      out.write("                <h1>LOGIN</h1>\r\n");
      out.write("\r\n");
      out.write("               ");
 if (errorMessage != null) { 
      out.write("\r\n");
      out.write("            <div class=\"alert alert-danger text-center\">\r\n");
      out.write("                <strong>Error:</strong> ");
      out.print( errorMessage );
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Username Field -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"inputName\" class=\"form-label\">Username:</label>\r\n");
      out.write("                    <input type=\"text\" name=\"inputName\" class=\"form-control\"\r\n");
      out.write("                        id=\"inputName\" required autocomplete=\"on\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Password Field with Show/Hide -->\r\n");
      out.write("                <div class=\"mb-3\">\r\n");
      out.write("                    <label for=\"inputPassword\" class=\"form-label\">Password:</label>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"password\" name=\"inputPassword\" class=\"form-control\"\r\n");
      out.write("                            id=\"inputPassword\" required autocomplete=\"on\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"togglePassword()\">\r\n");
      out.write("                            Show\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Submit Button -->\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-success w-100\">Login</button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"text-center mt-3\">\r\n");
      out.write("                    <a href=\"ForgotPassword.jsp\" class=\"text-danger\">Forgot Password?</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-4\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Login Form End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Show Password Script -->\r\n");
      out.write("    <script>\r\n");
      out.write("        function togglePassword() {\r\n");
      out.write("            var passwordInput = document.getElementById(\"inputPassword\");\r\n");
      out.write("            var button = document.querySelector(\".btn-outline-secondary\");\r\n");
      out.write("            if (passwordInput.type === \"password\") {\r\n");
      out.write("                passwordInput.type = \"text\";\r\n");
      out.write("                button.innerText = \"Hide\";\r\n");
      out.write("            } else {\r\n");
      out.write("                passwordInput.type = \"password\";\r\n");
      out.write("                button.innerText = \"Show\";\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
